kumuluzee:
  name: katalogProfilov
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://192.168.99.100:8081
    http:
      port: 8081

  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  metrics:
    web-instrumentation:
      - name: orders-endpoint
        url-pattern: /v1/katalogProfilov/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="orders">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="ec4e4103-b0ae-4d1e-beff-959e8bd7e149-ls.logit.io" port="16745" protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'
rest-properties:
  healthy: true