apiVersion: v1
kind: Service
metadata:
  name: katalog-service
  labels:
    app: katalog-profilov
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 32112
  selector:
    app: katalog-profilov